#  ____  _      _____ ____________         _____  _____
#  |  _ \| |    |_   _|___  |___  /   /\   |  __ \|  __ \
#  | |_) | |      | |    / /   / /   /  \  | |__) | |  | |
#  |  _ <| |      | |   / /   / /   / /\ \ |  _  /| |  | |
#  | |_) | |____ _| |_ / /__ / /__ / ____ \| | \ \| |__| |
#  |____/|______|_____/_____/_____/_/    \_|_|  \_|_____/

mysql:
  database: 's1176_Teste'
  host: 'us8.grape.urubuhost.com'
  port: 3306
  username: 'u1176_koWDXnIP9A'
  password: 'YVktyK!7GKL=+HakC6c2uZTo'

tasks:
  clear-security-codes: 60 # in seconds
  database-save: 60 # in sceonds
  users-verify: 120 # in seconds